version: "3.8"

volumes:
  data_storage:

services:
  authorization_server:
    image: quay.io/keycloak/keycloak:21.0.1
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command:
      - start-dev
      - "--log-level=INFO"
    ports:
      - 8080:8080
      - 9990:9990
      - 8443:8443
    depends_on:
      - data_storage
  data_storage:
    volumes:
      - data_storage:/var/lib/postgresql/data
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
