version: "3.8"

volumes:
  data_storage:

services:
  authorization_server:
    image: quay.io/keycloak/keycloak:21.0.1
    #restart: unless-stopped
    environment:
      KC_HTTP_RELATIVE_PATH: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://data_storage:5432/keycloak
      # KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: belaz
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminKey
      KC_HEALTH_ENABLED: "true"
    command:
      - start-dev
      - "--log-level=INFO"
    ports:
      - 8080:8080
      - 9990:9990
      - 8443:8443
    depends_on:
      - data_storage
  data_storage:
    volumes:
      - data_storage:/var/lib/postgresql/data
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: belaz
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"