version: "3.8"

volumes:
  data_storage:

services:
  data_storage:
    volumes:
      - data_storage:/var/lib/postgresql/data
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"